site_name: Guardiões da Saúde - Grupo 4
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Equipe: planejamento/equipe.md
      - Políticas do Repositório: 
        - Política de Commits: planejamento/politicas_repositorio/politica_commits.md
      - Heatmap: planejamento/heatmap.md
      - Lista de Apps Avaliados: planejamento/lista-de-apps-avaliados.md
      - Termo de Uso: planejamento/termo-de-uso.md
      - Ferramentas do Projeto: planejamento/ferramentas.md
      - Rich Picture: planejamento/rich-picture.md
