site_name: Guardiões da Saúde - Grupo 2
site_author: Ana Borges, Ana Joyce, Davi, Fabio, Gabriela, Luiz e Mateus
site_description: Site voltado para a documentação do Grupo 2 de Requisitos de Software
repo_url: https://requisitos-de-software.github.io/2025.1-Guardioes-da-Saude/
repo_name: 2025.1-Guardioes-da-Saude

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Equipe: planejamento/equipe.md
      - Políticas do Repositório: 
        - Política de Commits: planejamento/politicas_repositorio/politica_commits.md
        - Política de Branches: planejamento/politicas_repositorio/politica_branches.md
      - Heatmap: planejamento/heatmap.md
      - Lista de Apps Avaliados: planejamento/lista-de-apps-avaliados.md
      - Termo de Uso: planejamento/termo-de-uso.md
      - Ferramentas do Projeto: planejamento/ferramentas.md
      - Rich Picture: planejamento/rich-picture.md
  - Verificação: 
      - Lista de Verificação - Entrega 1: planejamento/lista-de-verificacao.md
  - Gravações:
    - Entregas: gravacoes/entregas/entregas.md
    - Reuniões e ATAS: gravacoes/reunioes/reunioes.md

markdown_extensions:
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption